name: Python Unittest

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Specify the Python version you're using
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run unittests
      run: |
        python3 -m unittest discover -s top-interview-questions/array -p '*.py'
